config/routes.rb
Rails.application.routes.draw do
  

  resources :reviews

  devise_for :providers
  
  devise_scope :provider do
    get "/sign_up" => "devise/registrations#new"
  end
  
  resources :procedures 
  resources :providers

  namespace :admin do 
    
    root 'static_pages#welcome'

    resources :providers do 
      resources :procedures
    end
  end
     

  get "/procedure_list" => "static_pages#procedure_list"

  get "/faq" => "static_pages#faq"
  get "/search_by_name" => "providers#search_by_name"
  get "/search_by_address" => "providers#search_by_address"

  root 'static_pages#welcome'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  class NotAuthorized < StandardError; end
	geocoded_by :address
	after_validation :geocode
	reverse_geocoded_by :latitude, :longitude, :address => :address
	after_validation :reverse_geocode

	has_many :procedures
  
  # Including default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end



end
 

app/controllers/admin/providers_controller.rb
class Admin::ProvidersController < AdminController
  def index
    if params[:search]
      @providers = Provider.search(params[:search]).order("created_at DESC")
    else
      @providers = Provider.all.order('created_at DESC')
    end
  end

  def search_by_address

    address = params[:address]
    @providers = Provider.near(address, 50)
    render 'providers/search_by_address'
  end

    

  def show
    @procedures = Procedure.all
      @provider = Provider.includes(:procedures).find(params[:id])
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  
  before_filter :authenticate_provider!, :except => [:index, :show, :search_by_address, :search_by_name]
	
  def index
  @providers = Provider.all
  if params[:search]
    @providers = Provider.search(params[:search]).order("created_at DESC")
  else
    @providers = Provider.all.order('created_at DESC')
  end
  end

	def search_by_address

      @address = params[:address]
      @providers = Provider.near(@address, 50)
      render 'providers/search_by_address'
    end

    

	def show
	  @procedures = Procedure.all
      @provider = Provider.includes(:procedures).find(params[:id])
	end

	def provider_params
		params.require(:provider).permit(:name, :address)
	end
end

app/helpers/admin/providers_helper.rb
module Admin::ProvidersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/index.html.erb
<div class="col-md-12 col-md-push-4">
          <%= form_tag search_by_address_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :address, params[:address] %>
          <%= submit_tag "Search Providers by Address", :name => nil, :class => "btn btn-success btn-lg" %>
          </p><% end %>
          <br><br>
          
          
</div>

<div class="col-md-12 col-md-push-4">
          <%= form_tag providers_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :search, params[:search], placeholder: "Search Providers" %>
          <%= submit_tag "Search Providers by Name", :class => "btn btn-success btn-lg" %>
          </p><% end %>
          <br><br>
          
          
</div>



<% @providers.each do |provider| %>
  
  <% next if provider.admin == true %>
  
  <h3><%= link_to provider.name, provider_path(provider) %></h3> 
  <h4><%= provider.address %></h4><br>

<% end %>

app/views/providers/search_by_address.erb
<div class="col-md-12 col-md-push-4">
          <%= form_tag search_by_address_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :address, params[:address] %>
          <%= submit_tag "Search Providers by Address", :name => nil, :class => "btn btn-success btn-lg" %>
          </p><% end %>
          <br><br>
          
          
</div>

<div class="col-md-12 col-md-push-4">
          <%= form_tag providers_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :search, params[:search], placeholder: "" %>
          <%= submit_tag "Search Providers by Name", :class => "btn btn-success btn-lg" %>
          </p><% end %>
          <br><br>
          
          
</div>



<% @providers.each do |provider| %>
      
        <h3><%= link_to provider.name, provider_path(provider) %></h3> 
        <h4><%= provider.address %></h4><br>

<% end %>

app/views/providers/search_by_name.html.erb
<div class="col-md-12 col-md-push-4">
          <%= form_tag search_by_address_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :address, params[:address] %>
          <%= submit_tag "Search Providers by Address", :name => nil, :class => "btn btn-success btn-lg" %>
          </p><br><br>
          
          <% end %>
</div>

<div class="col-md-12 col-md-push-4">
          <%= form_tag search_by_name_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :search, params[:search], placeholder: "" %>
          <%= submit_tag "Search Providers by Name", :name => nil, :class => "btn btn-success btn-lg" %>
          </p><br><br>
          
          <% end %>
</div>



<% @providers.each do |provider| %>
      
        <h3><%= link_to provider.name, provider_path(provider) %></h3> 
        <h4><%= provider.address %></h4><br>

<% end %>

app/views/providers/show.html.erb
<div class="row title-row">
  

  <div class="col-md-12 header-col">
    <h1 id="p-name"><strong><%= @provider.name %></strong></h1>
  </div>

  <div class="col-md-12 header-col">
    <h4><%= @provider.address %></h4>
  </div>

</div>

<br><br><br>

<div class="row">
<table class="pro-show-table col-md-12">
  <thead>
    <tr>
      <th>Procedure Name</th>
      
      <th>Insurance Price</th>
      <th>Cash Price</th>
      <th>Price Description</th>
      
    </tr>
  </thead>

  <tbody>
    <% @provider.procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.name %></td>
        <td><%= procedure.insurance_price %></td>
        <td><%= procedure.cash_price %></td>
        <td><%= procedure.price_description %></td>
      
        <td><%= link_to 'Show', procedure %></td>
        <% if provider_signed_in? %>
        <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
        <td><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br><br><br>

<div class="row">

  <div class="col-md-12 col-md-push-2">
    <p id="pricing-help">If you spot any pricing data you believe to be incorrect; please notify us at healhcostconnect@gmail.com</p>
  </div>

</div>