config/routes.rb
Rails.application.routes.draw do
  

  resources :reviews

  devise_for :providers
  
  devise_scope :provider do
    get "/sign_up" => "devise/registrations#new"
  end
  
  resources :procedures 
  resources :providers

  namespace :admin do 
    
    root 'static_pages#welcome'

    resources :providers do 
      resources :procedures
    end
  end
     

  get "/procedure_list" => "static_pages#procedure_list"

  get "/faq" => "static_pages#faq"
  get "/search_by_name" => "providers#search_by_name"
  get "/search_by_address" => "providers#search_by_address"

  root 'static_pages#welcome'

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
	belongs_to :provider
	has_many :reviews, dependent: :destroy


  def self.with_code(code)
    where(:code => code).order("created_at DESC")
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end


end

app/controllers/admin/procedures_controller.rb
class Admin::ProceduresController < AdminController
  def index
    if params[:search]
      @procedures = Procedure.search(params[:search]).order("created_at DESC")
    elsif params[:code]
      set_provider(params[:provider_id])
      @procedures = @provider.procedures.with_code(params[:code])
    else
      set_provider(params[:provider_id])
      @procedures = @provider.procedures.order('created_at DESC')
    end
  end

  
  def show
    @procedure = Procedure.includes(:provider).find(params[:id])
  end

  
  def new
    @provider = Provider.find(params[:provider_id])
    @procedure = @provider.procedures.build
    respond_to do |format|
          format.html {render :new}
          format.json { head :ok}
        end
  end

  
  def edit
    @procedure = Procedure.find(params[:id])
    @provider = Provider.find(params[:provider_id])
  end

  
  def create
    provider = Provider.find(params[:provider_id])
    @procedure = provider.procedures.build(procedure_params)
    if @procedure.save
      flash[:success] = "#{@procedure.name} successfully created for #{provider.name}"
      redirect_to new_admin_provider_procedure_path(provider)
    else
      flash[:error] = "Something went wrong creating procedure"
      render :new
    end
  end

  
  def update
    @procedure = Procedure.find(params[:id])
    provider = Provider.find(@procedure.provider_id)
      if @procedure.update(procedure_params)
        flash[:success] = "#{@procedure.name} for #{provider.name} updated"
        redirect_to admin_provider_procedures_path(provider)
      else
        flash[:error] = "Something went wrong"
        render :edit
      end
    
  end

  
  def destroy
    @procedure = Procedure.find(params[:id])
    provider = Provider.find(@procedure.provider_id)
    if @procedure.destroy
      flash[:success] = "#{@procedure.name} destroyed for #{provider.name}"
      redirect_to admin_provider_procedures_path(provider)
    else
      flash[:error] = "Something went wrong destroying procedure"
      redirect_to :back
    end
  end

  private
    
  def find_procedure
   @procedure = Procedure.find(params[:id])
  end

  def set_provider(id)
    @provider = Provider.find(id)
  end


  
  def procedure_params
    params.require(:procedure).permit(:name, :code, :cash_price, 
                                      :insurance_price, :price_description, :provider_id)
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_filter :authenticate_provider!, :except => [:index, :show]
  before_action :find_procedure, only: [:edit, :update, :destroy]
  before_action :authorize_resource!, except: [:index, :show, :new, :create]


  def index
    if params[:search]
      @procedures = Procedure.search(params[:search]).order("created_at DESC")
    elsif params[:code]
      @procedures = Procedure.with_code(params[:code])
    else
      @procedures = Procedure.all.order('created_at DESC')
    end
  end

  
  def show
    @procedure = Procedure.includes(:provider).find(params[:id])
  end

  
  def new
    @provider = current_provider
    @procedure = @provider.procedures.new(params[:id])
    respond_to do |format|
          format.html {render :new}
          format.json { head :ok}
        end
  end

  
  def edit
    @procedure = Procedure.includes(:provider).find(params[:id])
  end

  
  def create
    @procedure = @provider.procedures.new(procedure_params)
    @procedure.provider_id = current_provider.id

    if @procedure.save
      flash[:success] = 'Procedure was successfully created.' 
      redirect_to @procedure
    else
      flash[:error] = "Something went wrong."
      render :new
    end
    
  end

  
  def update
    @procedure = Procedure.includes(:provider).find(params[:id])
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: 'Procedure was successfully updated.' }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @procedure = Procedure.find(params[:id])
    if @procedure.destroy
      flash[:success] = "Procedure destroyed"
      redirect_to procedure_list_path
    else
      flash[:error] = "Something went wrong"
      redirect_to :back
    end
  end

  private
    
  def find_procedure
   @procedure = Procedure.find(params[:id])
  end

  def authorize_resource!
   unless current_provider == @procedure.provider
     raise Provider::NotAuthorized and return false
   end
  end

  
  def procedure_params
    params.require(:procedure).permit(:name, :code, :cash_price, 
                                      :insurance_price, :price_description)
  end
end

app/helpers/admin/procedures_helper.rb
module Admin::ProceduresHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_for(@procedure) do |f| %>
  <% if @procedure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>

      <ul>
      <% @procedure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :procedure_name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :cash_price %><br>
    <%= f.text_field :cash_price %>
  </div>
   <div class="field">
    <%= f.label :insurance_price %><br>
    <%= f.text_field :insurance_price %>
  </div>
  <div class="field">
    <%= f.label :price_description %><br>
    <%= f.text_field :price_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<h1>Edit Procedure</h1>

<%= render 'form' %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<div class="row">
  <div class="col-sm-12 col-sm-push-4">
    <h1>Procedures</h1>
  </div>
</div>
<div class="row col-md-12">

  <table class="pro-show-table col-md-8 table-striped table bordered table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Provider</th>
        <th>Insurance Price</th>
        <th>Cash Price</th>
        <th>Price Description</th>
        
      </tr>
    </thead>

    <tbody>
      <% @procedures.each do |procedure| %>
        <tr>
          <td><%= procedure.name %></td>
          <td><%= procedure.provider.name %></td>
          <td><%= number_to_currency(procedure.insurance_price) %></td>
          <td><%= number_to_currency(procedure.cash_price) %></td>
          <td><%= procedure.price_description %></td>
          
          <td><%= link_to 'Show', procedure %></td>
          <% if provider_signed_in? %>
          <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
          <td><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>
<br><br><br>
<br><br><br>

<div class="row">
  <div class="col-md-12">
    <p>If you spot any pricing data you believe to be incorrect; please notify us at healhcostconnect@gmail.com</p>
  </div>
</div>

app/views/procedures/new.html.erb
<h1>New procedure</h1>

<%= render 'form' %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong></strong>
  <%= @procedure.provider.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @procedure.name %>
</p>

<p>
  <strong>Insurance Price:</strong>
  <%= number_to_currency(@procedure.insurance_price) %>
</p>

<p>
  <strong>Cash Price:</strong>
  <%= number_to_currency(@procedure.cash_price) %>
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> 