config/routes.rb
Rails.application.routes.draw do
  

  resources :reviews

  devise_for :providers
  
  devise_scope :provider do
    get "/sign_up" => "devise/registrations#new"
  end
  
  resources :procedures 
  resources :providers

  namespace :admin do 
    
    root 'static_pages#welcome'

    resources :providers do 
      resources :procedures
    end
  end
     

  get "/procedure_list" => "static_pages#procedure_list"

  get "/faq" => "static_pages#faq"
  get "/search_by_name" => "providers#search_by_name"
  get "/search_by_address" => "providers#search_by_address"

  root 'static_pages#welcome'

end

app/views/layouts/_flash.html.erb
<% if flash[:success] %>
  <div class="row">
    <div class="col-xs-12 alert alert-success">
    <%= flash[:success] %>
    </div>
  </div>
<% elsif flash[:error] %>
  <div class="row">
    <div class="col-xs-12 alert alert-danger">
      <%= flash[:error] %>
    </div>
  </div>

<% end %>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <script type="text/javascript">

    
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-104681617-2', 'auto');
    ga('send', 'pageview');


    
  </script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HealthCostConnect", root_path, class: "navbar-brand", id: "nav-title" %>
     
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Search Providers", providers_path, :id => "search-providers" %></li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-text" id="nav-providers">Providers <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            
            
            <% if provider_signed_in? %>
            <li><%= current_provider.name %></li>
            <li><%= link_to "New Procedure", new_procedure_path, :class => "nav-text" %></li>
            <li><%= link_to "Provider Settings", edit_provider_registration_path, :class => "nav-text" %></li>
            <li><%= link_to "Provider Log out", destroy_provider_session_path, :method => :delete, :class => "nav-text" %></li>
            <% else %>
            <li><%= link_to "Provider Log in", new_provider_session_path, :class => "nav-text" %></li>
            <li><%= link_to "Provider Sign Up", sign_up_path, :class => "nav-text" %></li>
            <li><%= link_to "Provider FAQ", faq_path, :class => "nav-text" %>
            </li>
            <% end %>

          </ul>
        </li>
      </ul>
      
      
    </div>
  </div>
</nav>

<%= render partial: 'layouts/flash', locals: {:flash => flash} %>

app/views/layouts/_search.erb
<div class="col-md-12 col-md-push-4">
          <%= form_tag search_by_address_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :address, params[:address] %>
          <%= submit_tag "Search Providers by Address", :name => nil, :class => "btn btn-success btn-lg" %>
          </p><br><br>
          
          <% end %>
</div>

<div class="col-md-12 col-md-push-4">
          <%= form_tag search_by_name_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :search, params[:search], placeholder: "" %>
          <%= submit_tag "Search Providers by Name", :name => nil, :class => "btn btn-success btn-lg" %>
          </p><br><br>
          
          <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthCostConnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  
  <div class="row">
    <div class="col-xs-12 alert alert-success">
      <%= link_to "Admin Home", admin_root_path %>
    </div>
  </div>

  
  


  <%= yield %>


</div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthCostConnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= render 'layouts/google_analytics' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  


  <%= render 'layouts/header' %>
  


  <%= yield %>


</div>


</body>
</html>